version: '3.9'
services:
  api_gateway:
    image: devopsfaith/krakend:2.0.0
    container_name: api_gateway_ct
    volumes:
      - ./../apigateway_frontoffice/krakend:/etc/krakend/
    depends_on:
      - payment_service
      - inventory_service
    ports:
      - "8080:8081"
  payment_service:
    build:
      context: ./../paymentservice
    container_name: payment_service_ct
    ports:
      - "5000:5000"
  inventory_service:
    build:
      context: ./../inventoryservice
    container_name: inventory_service_ct
    ports:
      - "5001:5000"
  order_service:
    build:
      context: ./../FaaSinventorypdate
    container_name: order_service_ct
    ports:
      - "5002:5000"

