version: '3.9'
services:
  api_gateway:
    image: devopsfaith/krakend:2.0.0
    container_name: api_gateway_ct
    volumes:
      - ./../apigateway_frontoffice/krakend:/etc/krakend/
    depends_on:
      - payment_service
      - inventory_direct_service
      - inventory_pubsub_service
    ports:
      - "8080:8081"
  payment_service:
    build:
      context: ./../paymentservice
    container_name: payment_service_ct
    ports:
      - "5000:5000"
  inventory_direct_service:
    build:
      context: ../inventorydirectservice
    container_name: inventory_direct_service_ct
    ports:
      - "5001:5000"
    volumes:
      - "./../dbase:/usr/src/myapp/dbase"
  inventory_pubsub_service:
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/group-6-344214-ad49ed243a8c.json
      - PUBSUB_PROJECT_ID=group-6-344214
    build:
      context: ../inventorypubsubservice
    container_name: inventory_pubsub_service_ct
    ports:
      - "5002:5000"
    volumes:
      - "./../dbase:/usr/src/myapp/dbase"
      - ./group-6-344214-ad49ed243a8c.json:/opt/group-6-344214-ad49ed243a8c.json
  register_service:
    build:
      context: ../registerservice
    container_name: register_service_ct
    ports:
      - "5003:5000"
    depends_on:
      - api_gateway
  fulfillment_ui:
    build:
      context: ../fulfillment_ui
    container_name: fulfillment_ui_ct
    ports:
      - "5004:5000"
    depends_on:
      - api_gateway
